### ISSUE TITLE
검색결과를 매칭하지 못하는 문제

### ISSUE THREAD

**Issue by ryuneeee** [hkjinlee/calibre-ridibooks-plugin#1]
안녕하세요!

우연히 들어와서 받아 써보려고 하는데 제대로 동작하지 않는듯 싶네요.

Calibre 플러그인 로그를 보니 쿼리는 제대로 날라가는것 같은데,
리디북스 페이지 업데이트로 인해 파싱 쪽 로직이 어긋난것 같아요.
일단 유닛테스트가 제대로 동작하지 않고 있고요. 리디북스 쪽 페이지를 보니 DOM Element가 조금 바뀐것 같네요. 

```
################################################################################
### Running test with: {u'identifiers': {u'ridibooks': u'593000535'}}
################################################################################
Ridibooks url: u'http://ridibooks.com/v2/Detail?id=593000535'
[u'\ub9c8\uc774\ud074 \uc0cc\ub378', u'\uae40\uba85\ucca0']
[u'\uc800', u'\uc5ed']
1
[u'\ub9c8\uc774\ud074 \uc0cc\ub378', u'\uae40\uba85\ucca0(\uc5ed\uc790)']
ISBN is 9788937836367
Error parsing publisher/date for url: u'http://ridibooks.com/v2/Detail?id=593000535'
Traceback (most recent call last):
  File "calibre_plugins.ridibooks.worker", line 157, in parse_details
  File "calibre_plugins.ridibooks.worker", line 283, in parse_publisher_date
IndexError: list index out of range

Downloading cover from: http://misc.ridibooks.com/cover/593000535/xxlarge
```

```################################################################################
### Running test with: {u'title': u'\ud14c\uba54\ub808\ub974 \ud070\ubc14\ub2e4\ubc40'}
################################################################################
Search from /search/?q=%ED%85%8C%EB%A9%94%EB%A0%88%EB%A5%B4+%ED%81%B0%EB%B0%94%EB%8B%A4%EB%B1%80
Querying: http://ridibooks.com/search/?q=%ED%85%8C%EB%A9%94%EB%A0%88%EB%A5%B4+%ED%81%B0%EB%B0%94%EB%8B%A4%EB%B1%80
<Element div at 0x1164f3730>
Compare 테메레르 6권 - 큰바다뱀들의 땅 (나오미 노빅) with 테메레르 큰바다뱀 ()
Compare 테메레르 1권 - 왕의 용 (나오미 노빅) with 테메레르 큰바다뱀 ()
Ridibooks url: u'http://ridibooks.com/v2/Detail?id=606000890&_s=ret&_q=%ED%85%8C%EB%A9%94%EB%A0%88%EB%A5%B4%20%ED%81%B0%EB%B0%94%EB%8B%A4%EB%B1%80'
[u'\ub098\uc624\ubbf8 \ub178\ube45', u'\uacf5\ubcf4\uacbd']
[u'\uc800', u'\uc5ed']
1
[u'\ub098\uc624\ubbf8 \ub178\ube45', u'\uacf5\ubcf4\uacbd(\uc5ed\uc790)']
ISBN is 9788901114682
Error parsing publisher/date for url: u'http://ridibooks.com/v2/Detail?id=606000890&_s=ret&_q=%ED%85%8C%EB%A9%94%EB%A0%88%EB%A5%B4%20%ED%81%B0%EB%B0%94%EB%8B%A4%EB%B1%80'
Traceback (most recent call last):
  File "calibre_plugins.ridibooks.worker", line 157, in parse_detai
```

캘리버 로그는 다음과 같습니다.
```
****************************** RidiBooks (0, 0, 1) ****************************** 
Found 0 results 
Downloading from RidiBooks took 1.37325501442 
Search from /search/?q=%EC%96%B8%EC%96%B4%EC%9D%98+%EC%98%A8%EB%8F%84+%EC%9D%B4%EA%B8%B0%EC%A3%BC
Querying: http://ridibooks.com/search/?q=%EC%96%B8%EC%96%B4%EC%9D%98+%EC%98%A8%EB%8F%84+%EC%9D%B4%EA%B8%B0%EC%A3%BC

Compare 언어의 온도 (이기주) with 언어의 온도 (이기주)
Ridibooks url: u'http://ridibooks.com/v2/Detail?id=1930000002&_s=ret&_q=%EC%96%B8%EC%96%B4%EC%9D%98%20%EC%98%A8%EB%8F%84%20%EC%9D%B4%EA%B8%B0%EC%A3%BC'
[u'\uc774\uae30\uc8fc']
[u'\uc800']
Error parsing authors for url: u'http://ridibooks.com/v2/Detail?id=1930000002&_s=ret&_q=%EC%96%B8%EC%96%B4%EC%9D%98%20%EC%98%A8%EB%8F%84%20%EC%9D%B4%EA%B8%B0%EC%A3%BC'
Traceback (most recent call last):
  File "calibre_plugins.ridibooks.worker", line 126, in parse_details
  File "calibre_plugins.ridibooks.worker", line 266, in parse_authors
ValueError: u'\uc5ed' is not in list

Could not find title/authors/ridibooks id for u'http://ridibooks.com/v2/Detail?id=1930000002&_s=ret&_q=%EC%96%B8%EC%96%B4%EC%9D%98%20%EC%98%A8%EB%8F%84%20%EC%9D%B4%EA%B8%B0%EC%A3%BC'
Ridibooks: u'1930000002' Title: u'\uc5b8\uc5b4\uc758 \uc628\ub3c4' Authors: [] 
```

**Comment by hkjinlee** [comment]
리디북스 상세페이지 코드가 많이 바뀌었네요. 작업중입니다 :)

**Comment by hkjinlee** [comment]
문제해결한 버전 commit해두었습니다. 한번 확인해봐 주시겠어요?

```
****************************** RidiBooks ****************************** 
Request extra headers: [('User-agent', u'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0')] 
Found 1 results 
Downloading from RidiBooks took 0.656013011932 


--- 
Title               : 거침없이 제주이민
Author(s)           : 기락
Publisher           : 꿈의지도
Languages           : Korean
Rating              : 
Published           : 2012-02-05T00:00:00+00:00
Identifiers         : ridibooks:609000001
Comments            :  "‘여기서 한번 쯤 살아봤으면 좋겠다.’ 제주 여행자의 하나같은 바람이다. 그 바람을 실천에 옮겨 과감한 육지탈출로 제주에서 행복 찾은 15인의 거침없고 생생한 제주 정착기. 제주행 비행기에 오른 이유부터 제주에서 살 집을 구하고, 일자리를 찾거나 스스로 만들고, 아이들 교육 시키는 것까지, 선배 이주자들의 경험담은 끝이 없다. 그들은 제주에서의 삶이 ‘이주’가 아니라 ‘이민’이라고 불러도 무방할 정도로 육지와는 문화와 환경이 다르지만, 무한 경쟁에서 한발 비켜나 다른 삶을 살 수 있다는 것만으로도 축복이자 행복이라 말한다. 이들 제주 이주자들은 ‘육지에서 죽자 살자 견디지 마라. 다른 삶도 있다. 그 다른 삶은 그리 멀리 있지 않다. 그러니 지금 바로 건너오라’고 손짓한다. 

제주에서 뭐 해서 먹고 살아요? 
제주에 살고 싶은 사람들의 가장 큰 고민이다. 바로 이 ‘먹고 사는 고민’만 해결된다면 언제든지 갈 수 있을 것 같다. 용기만으로 해결될 수 있는 문제가 아니다. 가족이 함께라면 넘어야 할 더 큰 벽이다. 선배 이주자들도 같은 고민을 안고 제주행 비행기에 올랐다. 제주 입도 1년 전부터 치밀하게 준비했던 사람도 있고, 제주에 도착해 찾아보자며 무작정 비행기를 탄 이주민도 있다. 과정은 다르지만 결론은 하나다. ‘제주에서도 누구든 먹고 살 수 있다’는 거다. 무인카페, 게스트하우스, 직장인, 만화가, 도서관, 래퍼, 레스토랑, 민박집, 감귤농장, 케이크가게, 식품회사, 초콜릿가게, 노인요양시설, 농산물 유통, 부동산까지. 선배 이주자들이 다양한 분야에서 도전하고 정착하는 과정을 통해 제주의 현실을 이해하고 용기를 얻을 수 있을 것이다. 

제주에서는 어디에 살아요? 
또 하나의 현실적인 문제가 집이다. 제주 여행에서 보았던 바닷가 앞 그림 같은 펜션을 꿈꾼다면 그만한 재정이 뒷받침 되어야 한다. 지금 제주로 이주를 꿈꾸는 사람들은 돈 많은 은퇴 이민자가 전부는 아니다. 오히려 육지의 각박한 삶을 떠나 좀 더 자연에 가깝고, 여유로운 삶은 찾는 젊은 가족들이 많다. 그들의 주머니 사정은 넉넉하지 않다. 그래서 선배 이주자들은 처음부터 집을 사거나 짓지 말고, 최소한 1년 정도는 집을 빌려서 ‘연세’를 내고 살아보라고 충고한다. 그리고 무작정 시골로 가기 보다는 제주시나 서귀포시, 혹은 그 언저리에 집을 구하는 게 고립감을 피하는 데 좋다고 말한다. 제주에 오자마자 집을 지었던 이주민은 육지와는 많이 다른 제주에서의 집짓기 경험을 생생하게 풀어 놓는다. ‘우리처럼 실수하지 말라’고 충고한다. 

제주에서 이주자들에게 누가 도움을 주나요? 
육지에서의 팍팍한 삶이 싫어서 제주도를 선택하는 것이지, 사람이 싫어서 비행기를 탄 것은 아니다. 낯선 곳이지만 고민을 나눌 사람이 있어야 한다. 같은 한국이지만 이민이라고 불러도 좋을 만큼 제주의 문화와 생활환경이 많이 다르기 때문이다. ‘제주이민’의 어려움을 먼저 겪은 선배 이주자들은 이런 고민 상담이 반갑다. 누군가 궁금한 것을 물어오면 제 일처럼 나서서 도와준다. <거침없이 제주이민>에 소개된 15인은 제주 이주를 꿈꾸는 이들의 맨토와도 같은 존재들이다. 이들은 지금도 제주 이주를 꿈꾸는 후배 이주자들이 궁금해 하는 모든 것에 대해 친절히 답변해 주고 있다. 이 책에 나온 15인의 선배 이주자들을 아는 것만으로도 이미 제주 이민자 네트워크에 접속한 것과 진배없다. 이들이 운영하는 카페나 게스트하우스를 찾아가 생생한 이야기를 들으면 ‘제주이민’이 꿈이 아닌 현실로 다가온다. 

그래서 제주에서 행복한가요? 
‘제주에서의 생활’하면 누구나 여행을 떠올릴 것이다. 육지에서는 많은 비용과 시간을 내서 연간 계획을 세워야 가능한 제주 여행이 일상이 되기 때문. 많은 이주자들은 설령 제주에 정착하지 못해 떠난다 하더라도 이런 즐거움이 보상으로 남는다고 입을 모은다. 그러나 선배 이주자들이 말하는 삶의 가장 큰 변화는 소중한 사람들과 함께 하는 시간이 절대적으로 늘어났다는 것이다. 가족이 한 울타리에 있으면서도 모래처럼 흩어져 살았던 육지에서와 달리, 제주에서는 가족이 하나의 생명체처럼 유기적으로 연결되어 있음을 느낀다고 한다. 선배 이주자들은 ‘제주에서 자신과 가족에 대한 애정과 신뢰를 회복했으며 인생에서 가장 행복한 시절을 보내고 있다’고 고백한다. 이들은 제주에 평생 뿌리 내리지 않더라도, 살고 싶다는 생각이 들면 잠깐 이라도 살아보라고 권한다. 결코 후회하는 일은 없을 것이라고. <거침없이 제주이민>에는 선배 이주자들이 제주에서 느끼는 행복의 실체가 고스란히 담겨 있다. 이 책을 다 읽고 나면 제주에서 보내는 ‘행복 바이러스’에 끌려 제주행 비행기 티켓을 사는 자신을 발견할 지도 모를 일이다." 
Search from /search/?q=%EA%B1%B0%EC%B9%A8%EC%97%86%EC%9D%B4+%EC%A0%9C%EC%A3%BC%EC%9D%B4%EB%AF%BC
Querying: http://ridibooks.com/search/?q=%EA%B1%B0%EC%B9%A8%EC%97%86%EC%9D%B4+%EC%A0%9C%EC%A3%BC%EC%9D%B4%EB%AF%BC

Compare 거침없이 제주이민 (기락) with 거침없이 제주이민 ()
Compare [체험판] 거침없이 제주이민 (기락) with 거침없이 제주이민 () 

******************************************************************************** 
```

**Comment by ryuneeee** [comment]
잘되는군요! 감사합니다.

**Comment by pakistoh** [comment]
리디북스 코드가 바뀌었는지 .... 에러만 내뿜네요....
